version: 2.1
 
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
 
    working_directory: ~/project/PetClinic
 
    environment:
      MAVEN_OPTS: -Xmx3200m
 
    steps:
      - checkout
 
      - restore_cache:
          keys:
            - PetClinic-{{ checksum "" }}  # Zmiana klucza
 
      - save_cache:
          paths:
            - ~/.m2
          key: PetClinic-{{ checksum "" }}  # Zmiana klucza
 
      - run: mvn dependency:go-offline
 
      - run: mvn integration-test
 
workflows:
  sample:
    jobs:
      - build-and-test
