version: 2.1
 
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
 
    working_directory: ~/project  # Ścieżka do katalogu głównego, gdzie jest plik pom.xml
 
    environment:
      MAVEN_OPTS: -Xmx3200m
 
    steps:
      - checkout
 
      - restore_cache:
          keys:
            - PetClinic-{{ "pom.xml" }}
            - v1-dependecies-
 
      - save_cache:
          paths:
            - ~/.m2
          key: PetClinic-{{ "pom.xml" }}
 
      - run: mvn dependency:go-offline
 
      - run: mvn integration-test
 
workflows:
  sample:
    jobs:
      - build-and-test
