version: 2.1
 
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
 
    working_directory: /PetClinic  # Zmiana ścieżki tutaj
 
    environment:
      MAVEN_OPTS: -Xmx3200m
 
    steps:
      - checkout
 
      - restore_cache:
          keys:
            - spring-pet-clinic-{{ checksum "pom.xml" }}
            - v1-dependecies-
 
      - save_cache:
          paths:
            - ~/.m2
          key: spring-pet-clinic-{{ checksum "pom.xml" }}
 
      - run: mvn dependency:go-offline
 
      - run: mvn integration-test
 
workflows:
  sample:
    jobs:
      - build-and-test
